export const SET_LAT_AND_LON = 'SET_LAT_AND_LON';  // 经纬度
// export const SET_LNG = 'SET_LNG';  // 经度
// export const SET_LAT = 'SET_LAT';  // 纬度
export const SET_PROVINCE = 'SET_PROVINCE';  // 省
export const SET_CITY = 'SET_CITY';  // 市
export const SET_DISTRICT = 'SET_DISTRICT';  // 区
export const SET_STREET_NUM = 'SET_STREET_NUM';  // 街道
export const SET_ADDR = 'SET_STREET_ADDR';  // 地址
export const SET_NAME = 'SET_NAME';  // 最小单位名字，比如小区名字,一般选择地址时用
export const SET_IS_DAY = 'SET_IS_DAY';  // 设置当前地址是不是白天
